server:
  port: 8088
  error:
    path: /error
spring:
  data:
    neo4j:
      # 数据库uri地址
      uri: bolt://39.102.46.180:7687  #测试用本地 # bolt://localhost:7687 服务器 bolt://39.102.46.180:7687
      # Neo4j配置
      username: neo4j
      password: cuscai #cuscai 123456
  datasource:
    url: jdbc:mysql://39.102.46.180:3306/CUQADatabase?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: cuqa
    password: cuqa_q8s63g
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.cusc.cuscai.mapper: DEBUG


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


remote-ai:
  qaai:
    url: http://39.102.46.180:7662
  kgai:
    url: http://10.108.217.31:5000

neo4j:
  url: bolt://39.102.46.180:7687  # bolt://39.102.46.180:7687 # bolt://localhost:7687
  username: neo4j
  password: cuscai #cuscai